aprs_callsign: null
aprs_filter: m/100
aprs_host: rotate.aprs2.net
aprs_port: 14580
baud: 9600
connection_type: tcp
debug: false
delay: 0
device: /dev/ttyUSB0
host: 127.0.0.1
listen: 0.0.0.0:5001
mqtt_forward: false
mqtt_host: 127.0.0.1
mqtt_pass: ''
mqtt_port: 1883
mqtt_tls: false
mqtt_user: ''
no_log: false
port: 1234
proxy_enabled: false
proxy_port: 5002
resume: 0
send: null
telemetry_interval: 120
